IPos/IPos/Controllers/ExchangeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using IPos.Models;

namespace IPos.Controllers
{
    public class ExchangeController : Controller
    {
        private const string BillSession = "BillSession";
        private const string BillCurrent = "BillCurrent";
        // GET: Exchange
        public ActionResult Index()
        {

            var billSession = Session[BillSession];
            var listBill = new List<Bill>();
            if (billSession != null)
            {
                listBill = (List<Bill>)billSession;
            }
            else
            {
                //Create new a bill and add to list bill
                var bill = new Bill
                {
                    BillNumber = 1,
                };
                listBill.Add(bill);
                Session[BillSession] = listBill;
                Session[BillCurrent] = bill.BillNumber;
            }
            ViewBag.BillCurrent = Session[BillCurrent];
            return View(listBill);
        }

        #region Build Bill
        //add Bill
        public ActionResult AddBill()
        {
            var billSession = Session[BillSession];
            var bill = new Bill();
            if (billSession != null)
            {
                var listBill = (List<Bill>)Session[BillSession];
                var maxBillNumber = listBill.Max(x => x.BillNumber);
                bill.BillNumber = maxBillNumber + 1;
                listBill.Add(bill);
            }
            else
            {
                //Create new a bill and add to list bill
                bill.BillNumber = 1;
                var listBill = new List<Bill>();
                listBill.Add(bill);
                Session[BillSession] = listBill;
            }
            Session[BillCurrent] = bill.BillNumber;
            return RedirectToAction("Index");
        }

        //delete Bill
        public ActionResult DeleteBill(int billNumber)
        {
            var billSession = Session[BillSession];
            if (billSession != null)
            {
                var listBill = (List<Bill>)Session[BillSession];
                listBill.RemoveAll(x => x.BillNumber == billNumber);

                if (listBill.Count == 0)
                {
                    var bill = new Bill
                    {
                        BillNumber = 1,
                    };
                    listBill.Add(bill);
                }
                Session[BillSession] = listBill;
                Session[BillCurrent] = listBill.Min(x => x.BillNumber);
            }
            return RedirectToAction("Index");
        }

        //set bill current 
        public ActionResult SetBillCurrent(int billNumber)
        {
            Session[BillCurrent] = billNumber;
            return RedirectToAction("Index");
        }

        //add bill item to list
        public ActionResult AddBillItem(string productCode, int quantity, int billNumber)
        {
            var billSession = Session[BillSession];
            if (billSession != null)
            {
                var listBill = (List<Bill>)billSession;
                var listBillItem = listBill.Single(x => x.BillNumber == billNumber).BillItems;
                if (listBillItem.Exists(x => x.Product_Unit.Product_Code == productCode))
                {
                    foreach (var billItem in listBillItem)
                    {
                        if (billItem.Product_Unit.Product_Code == productCode)
                        {
                            billItem.Quantity += quantity;
                        }
                    }
                }
                else
                {
                    var billItem = GetBillItemByProductCode(productCode);
                    billItem.Quantity = quantity;
                    listBillItem.Add(billItem);
                }
                Session[BillSession] = listBill;
            }
            else
            {
                //TODO: error
            }

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        //update Bill item
        public JsonResult UpdateBillItem(int billNumber, string productCode, int quantity, decimal discount)
        {
            var billSession = Session[BillSession];
            if (billSession == null)
                return Json(new { success = false, msg = "Lỗi: Session null" }, JsonRequestBehavior.AllowGet);
            var listBill = (List<Bill>)Session[BillSession];
            var bill = listBill.SingleOrDefault(x => x.BillNumber == billNumber);
            if (bill != null)
            {
                var billItem = bill.BillItems.SingleOrDefault(x => x.Product_Unit.Product_Code == productCode);
                if (billItem != null)
                {
                    billItem.Quantity = quantity;
                    billItem.Discount = discount;
                    Session[BillSession] = listBill;
                    return Json(new { success = true, msg = "" }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { success = false, msg = "Lỗi: Session null" }, JsonRequestBehavior.AllowGet);
        }

        //delete Bill item
        public JsonResult DeleteBillItem(int billNumber, string productCode)
        {
            var sessionBill = (List<Bill>)Session[BillSession];
            if (sessionBill == null)
                return Json(new { success = false, msg = "Session null" }, JsonRequestBehavior.AllowGet);
            try
            {
                sessionBill.Single(x => x.BillNumber == billNumber).BillItems.RemoveAll(x => x.Product_Unit.Product_Code == productCode);
                return Json(new { success = true }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { success = false, msg = "Lỗi: " + e.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        //Get Bill Item by product code
        private BillItem GetBillItemByProductCode(string productCode)
        {
            using (var dbContext = new IPosEntities())
            {

                return (from pu in dbContext.Product_Unit.Where(x => x.Product_Code == productCode)
                        from p in dbContext.Products.Where(x => x.ID == pu.Product_ID)
                        select new BillItem
                        {
                            Product = p,
                            Product_Unit = pu
                        }).FirstOrDefault();
            }
        }

        [HttpGet]
        public ActionResult BillItem_Partial(int billNumber)
        {
            var billSession = Session[BillSession];
            var listBillItem = new List<BillItem>();
            if (billSession != null)
            {
                var listBill = new List<Bill>();
                listBill = (List<Bill>)billSession;
                listBillItem = listBill.SingleOrDefault(x => x.BillNumber == billNumber).BillItems;
            }
            Session[BillCurrent] = billNumber;
            ViewBag.BillCurrent = Session[BillCurrent];
            return Json(new { success = true, html = RenderRazorViewToString("~/Views/Exchange/BillItem_Partial.cshtml", listBillItem) }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Extent
        private string RenderRazorViewToString(string viewName, object model)
        {
            ViewData.Model = model;
            using (var sw = new StringWriter())
            {
                var viewResult = ViewEngines.Engines.FindPartialView(ControllerContext,
                    viewName);
                var viewContext = new ViewContext(ControllerContext, viewResult.View,
                    ViewData, TempData, sw);
                viewResult.View.Render(viewContext, sw);
                viewResult.ViewEngine.ReleaseView(ControllerContext, viewResult.View);
                return sw.GetStringBuilder().ToString();
            }
        }
        #endregion
    }
    public class Bill
    {
        public int BillNumber { get; set; }
        public List<BillItem> BillItems = new List<BillItem>();
        public decimal? Discount { get; set; }
    }

    [Serializable]
    public class BillItem
    {
        public Products Product { get; set; }
        public Product_Unit Product_Unit { get; set; }
        public int Quantity { get; set; }
        public decimal Discount { get; set; }
    }
}

IPos/IPos/Views/Exchange/BillItem_Partial.cshtml
@model List<IPos.Controllers.BillItem>
<style type="text/css">
    .custom-change-quantity {
        font-weight:bold;
        font-size:20px;
        height:30px;
        padding-top:0px;
    }

    .form-control-price {
        height:30px;
        border-radius:5px;
        text-align:right;
    }
</style>
<input type="hidden" id="hdBillCurrenr" value="@ViewBag.BillCurrent" />
<input type="hidden" id="hdBillItemCurrent" />
<table class="table table-hover">
    @{ var stt = 1;}
    @foreach (var item in Model)
    {
        <tr>
            <td style="width:2%">@stt</td>
            <td style="width:2%"><a href="javascript:void(0)" onclick="DelBillItem(@ViewBag.BillCurrent,'@item.Product_Unit.Product_Code');"> <i class="fa fa-close" style="color:#ccc;margin-left:5px;" onclick="alert(2);"></i></a></td>
            <td style="width:9%">@item.Product_Unit.Product_Code</td>
            <td>@item.Product.Name</td>
            <td style="width:15%">
                <table>
                    <tr>
                        <td><button class="btn btn-sm custom-change-quantity" onclick="change_quantity(-1, '@item.Product_Unit.Product_Code')"><i class="fa fa-angle-down"></i></button></td>
                        <td>
                            <input id="billItem_quantity_@item.Product_Unit.Product_Code" class="form-control form-control-price" value="@item.Quantity.ToString("N0")" />
                        </td>
                        <td><button class="btn btn-sm custom-change-quantity" onclick="change_quantity(1, '@item.Product_Unit.Product_Code')"><i class="fa fa-angle-up"></i></button></td>
                    </tr>
                </table>
                
            </td>
            <td style="width:15%; text-align:right;">
                <input class="form-control form-control-price" id="billItem_price_@item.Product_Unit.Product_Code" value="@((item.Product_Unit.Sell_Price.GetValueOrDefault(0) - item.Discount ).ToString("N0"))" />

                @*<a class="priceBillItem" id="billItem-@item.Product_Unit.Product_Code" productCode=@item.Product_Unit.Product_Code price=@item.Product_Unit.Sell_Price discount="0" data-placement="left"  data-title="" data-container="body" type="button" data-html="true" href="javascript:void(0)">
                    
                </a>*@
                <span class="discountBillItem"></span>
            </td>
            <td id="billItem_totalPrice_@item.Product_Unit.Product_Code" style="width:15%; text-align:right; font-weight:bolder; vertical-align:middle">@((item.Product_Unit.Sell_Price.GetValueOrDefault(0) * item.Quantity).ToString("N0"))</td>
        </tr>
        stt++;
    }
</table>
<script type="text/javascript">
    /*Function*/
    function DelBillItem(billNumber, productCode) {
        $.ajax({
            url: '@Url.Action("DeleteBillItem","Exchange")',
            data: { billNumber: billNumber, productCode: productCode },
            type: 'GET',
            dataType: 'JSON',
            success: function (result) {
                if (result.success) {
                    GetBillDetail(billNumber);
                } else {
                    alert(result.msg);
                }
            },
            error: function () {
            }
        });
    }

    function UpdateBillItem(billNumber, productCode, quantity, discount) {
        $.ajax({
            url: '@Url.Action("UpdateBillItem", "Exchange")',
            data: { billNumber: billNumber, productCode: productCode, quantity: quantity, discount: discount },
            type: 'GET',
            dataType: 'JSON',
            success: function (result) {
                if (!result.success) {
                    alert(result.msg);
                    return;
                }
                document.getElementById("billItem_quantity_" + productCode).value = quantity;
                document.getElementById("billItem_totalPrice_" + productCode).innerHTML = SO_CSO(quantity * CSO_SO(document.getElementById("billItem_price_" + productCode).value));
            },
            error: function () {
            }
        });
    }

    function change_quantity(quantity, code) {
        var billNumber = $('#hdBillCurrenr').val();
        quantity = parseInt(quantity) + parseInt(document.getElementById("billItem_quantity_" + code).value);
        quantity = quantity < 1 ? 1 : quantity;
        var idBilItemInActive = $('#hdBillItemCurrent').val();
        UpdateBillItem(billNumber, code, quantity, 0);
    }

    //$(document).on('click', function (e) {
    //    $('[data-toggle="popover"],[data-original-title]').each(function () {
    //        //the 'is' for buttons that trigger popups
    //        //the 'has' for icons within a button that triggers a popup
    //        if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
    //            (($(this).popover('hide').data('bs.popover') || {}).inState || {}).click = false  // fix for BS 3.3.6
    //        }
    //    });
    //});

    //$("[data-toggle=popover]").popover({
    //    html: true,
    //    content: function () {
    //        var html = "<table>"
    //        html += "<tr>"
    //        html += "<td>Giá mới</td>"
    //        html += "<td colspan='3'><input class='form-control-price' id='billItemNewPrice' type='text'></td>"
    //        html += "</tr>"
    //        html += "<tr>"
    //        html += "<td>Giảm giá</td>"
    //        html += "<td>"
    //        html += "<input class='form-control-price' id='billItemDiscount' type='text'>"
    //        html += "</td>"
    //        html += "<td>"
    //        html += "<div class='btn-group'>"
    //        html += "<button class='btn btn-sm bg-olive btn-flat'>VND</button>"
    //        html += "<button class='btn btn-sm btn-flat'>%</button>"
    //        html += "</div>"
    //        html += "</td>"
    //        html += "</tr>"
    //        html += "</table>"
    //        return html;
    //    },
    //});

    //$('.priceBillItem').on('shown.bs.popover', function () {
    //    $('#hdBillItemCurrent').val($(this).attr("id"));
    //    $('#billItemNewPrice').val($.trim($(this).text()));

    //    PopoverBillItem_KeyUp();
    //    PopoverBillItem_Change();
    //});

    //function PopoverBillItem_KeyUp() {
    //    $('#billItemNewPrice').keyup(function () {
    //        var idBilItemInActive = $('#hdBillItemCurrent').val();
    //        var price = parseFloat($('#' + idBilItemInActive).attr("price"));
    //        var newPrice = parseFloat($('#billItemNewPrice').val());
    //        $('#' + idBilItemInActive).html(newPrice);
    //        $('#' + idBilItemInActive).attr("discount", price - newPrice);;
    //    });
    //}

    //function PopoverBillItem_Change() {
    //    $('#billItemNewPrice').change(function () {
    //        //update session
    //        var idBilItemInActive = $('#hdBillItemCurrent').val();
    //        var billNumber = $('#hdBillCurrenr').val();
    //        var productCode = $('#' + idBilItemInActive).attr("productCode");
    //        var discount = parseFloat($('#' + idBilItemInActive).attr("discount"));
    //        var quantity = 1;
    //        UpdateBillItem(billNumber, productCode, quantity, discount);
    //    });
    //}
</script>

IPos/IPos/Views/Exchange/Index.cshtml
@model List<IPos.Controllers.Bill>
@{
    ViewBag.Title = "Bán hàng";
    Layout = "";
}
<!DOCTYPE html>
@using System.Web.Optimization;
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    <style>
        .custom-remove-btn {
            
        }

        .custom-remove-btn :hover {
            cursor:pointer;
        }
    </style>
</head>
<body class="skin-blue-light layout-top-nav" style="padding-top: inherit; font-family:Arial, Helvetica, sans-serif; font-size:small" onload="javascript:max()">
    <div class="wrapper" style="height: auto; min-height: 100%;">
        <header class="main-header" id="main_header">
            <nav class="navbar navbar-static-top">
                <div class="navbar-header">
                </div>
                <div class="navbar-form navbar-left">
                    <div class="input-group">
                        <span class="input-group-addon"><i class="fa fa-search"></i></span>
                        <input id="txtSearch" class="form-control" type="text" placeholder="Tìm mặt hàng" style="width:340px;" />
                    </div>
                    <button class="btn btn-primary btn-flat no-border"><i class="fa fa-barcode"></i></button>
                </div>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li class="dropdown messages-menu" title="Phím tắt chức năng">
                            <a href="#" class="dropdown-toggle " data-toggle="dropdown">
                                <i class="glyphicon glyphicon-exclamation-sign"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <section class="content">
            <div class="row">
                <div class="col-md-9">
                    <div class="nav-tabs-custom">
                        <ul id="ulBill" class="nav nav-tabs">
                            @foreach (var item in Model)
                            {
                                <li billNumber="@item.BillNumber">
                                    <a href="javascript:void(0)" onclick="GetBillDetail(@item.BillNumber)">Hóa đơn @item.BillNumber <i class="fa fa-close" style="color:#ccc;margin-left:5px;" onclick="alert(1);"></i></a>
                                </li>
                            }
                            <li class=""><a href='@Url.Action("AddBill","Exchange")'><i class="fa fa-plus custom-close-btn"></i></a></li>
                        </ul>
                    </div>
                    <hr />
                    <div id="idBillDetail"></div>
                </div>
                <div class="col-md-3">
                    <div class="box box-default">
                        <div class="box-body"></div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    @Scripts.Render("~/Content/js")
    <script type="text/javascript">
        function max()
        {
            var obj = new ActiveXObject("Wscript.shell");
            obj.SendKeys("{f11}");
        }

        $('#txtSearch').keyup(function (e) {
            var productCode = $('#txtSearch').val();

            if (e.keyCode == 13) {
                AddBillItem(productCode);
                $('#txtSearch').focus();
            }
        });
        $("#ulBill li").click(function () {
            CssActiveBillMenu($(this).attr("billNumber"));
        });

        /*Function*/
        function AddBill() {
            $.ajax({
                url: '@Url.Action("AddBill","Exchange")',
                type:'GET',
                cache: false,
                success: function () {
                }
            });
        }

        function DeleteBill() {
            //if
        }

        function AddBillItem(productCode) {
            var billCurrent = $('#hdBillCurrenr').val();
            $.ajax({
                url: '@Url.Action("AddBillItem","Exchange")',
                data: { productCode: productCode, quantity: 1, billNumber: billCurrent },
                type:'GET',
                dataType: 'JSON',
                cache: false,
                success: function (rerult) {
                    GetBillDetail(billCurrent);
                }
            });
        }

        function GetBillDetail(billNumber) {
            $.ajax({
                url: '@Url.Action("BillItem_Partial", "Exchange")',
                data: { billNumber: billNumber},
                type: 'GET',
                contentType: 'application/json;charset=utf-8',
                cache: false,
                success: function (result) {
                    if (result.success) {
                        $('#idBillDetail').html(result.html);
                    } else {
                        alert(result.msg);
                    }
                },
                error: function (qXhr, exception) {
                    alert("Lỗi: " + qXhr);
                }
            });
        }

        function CssActiveBillMenu(billNumber) {
            $("#ulBill li").each(function () {
                if ($(this).attr("billNumber") == billNumber) {
                    $(this).addClass("active");
                } else {
                    $(this).removeClass("active");
                }
            });
        }

        /*Intinial*/
        jQuery(function ($) {
            $("#txtSearch").focus(function () { $(this).select(); });
            CssActiveBillMenu(@ViewBag.BillCurrent);
            GetBillDetail(@ViewBag.BillCurrent);
        });
    </script>
</body>
</html>